loader:
    verbose: true
logging:
    level:
        org:
            springframework:
spring:
    aop:
        proxy-target-class: true
    data:
        mongodb:
            host: ${DB_HOST}
            username: ${DB_USER}
            password: ${DB_PASSWORD}
            repositories:
                enabled: true
    jpa:
        properties:
            hibernate:
show_sql: true